package me.vz11.zoomies.util;

public class KeycodeUtils 
{
    public static String[] keyTable = {
        "",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Space",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "'",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        ",",
        "-",
        ".",
        "/",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "Unknown",
        ";",
        "Unknown",
        "=",
        "Unknown",
        "Unknown",
        "Unknown",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "[",
        "\\",
        "]",
        "Unknown",
        "Unknown",
        "`",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "World 1",
        "World 2",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Escape",
        "Enter",
        "Tab",
        "Backspace",
        "Insert",
        "Delete",
        "Right",
        "Left",
        "Down",
        "Up",
        "Page Up",
        "Page Down",
        "Home",
        "End",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Caps Lock",
        "Scroll Lock",
        "Num Lock",
        "Print Screen",
        "Pause",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "F11",
        "F12",
        "F13",
        "F14",
        "F15",
        "F16",
        "F17",
        "F18",
        "F19",
        "F20",
        "F21",
        "F22",
        "F23",
        "F24",
        "F25",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Num 0",
        "Num 1",
        "Num 2",
        "Num 3",
        "Num 4",
        "Num 5",
        "Num 6",
        "Num 7",
        "Num 8",
        "Num 9",
        "Num .",
        "Num /",
        "Num *",
        "Num -",
        "Num +",
        "Num Enter",
        "Num =",
        "Unknown",
        "Unknown",
        "Unknown",
        "Left Shift",
        "Left Control",
        "Left Alt",
        "Left Command",
        "Right Shift",
        "Right Control",
        "Right Alt",
        "Right Command",
        "Menu",
        "Last",
    };

public static boolean isKeyPressed(String key) {
    int glfwKey = getGLFWKeycode(key);
    if (glfwKey == -1) return false;
    
    return org.lwjgl.glfw.GLFW.glfwGetKey(org.lwjgl.glfw.GLFW.glfwGetCurrentContext(), glfwKey) == org.lwjgl.glfw.GLFW.GLFW_PRESS;
}

private static int getGLFWKeycode(String key) {
    switch(key.toLowerCase()) {
        case "a": return org.lwjgl.glfw.GLFW.GLFW_KEY_A;
        case "b": return org.lwjgl.glfw.GLFW.GLFW_KEY_B;
        case "c": return org.lwjgl.glfw.GLFW.GLFW_KEY_C;
        case "d": return org.lwjgl.glfw.GLFW.GLFW_KEY_D;
        case "e": return org.lwjgl.glfw.GLFW.GLFW_KEY_E;
        case "f": return org.lwjgl.glfw.GLFW.GLFW_KEY_F;
        case "g": return org.lwjgl.glfw.GLFW.GLFW_KEY_G;
        case "h": return org.lwjgl.glfw.GLFW.GLFW_KEY_H;
        case "i": return org.lwjgl.glfw.GLFW.GLFW_KEY_I;
        case "j": return org.lwjgl.glfw.GLFW.GLFW_KEY_J;
        case "k": return org.lwjgl.glfw.GLFW.GLFW_KEY_K;
        case "l": return org.lwjgl.glfw.GLFW.GLFW_KEY_L;
        case "m": return org.lwjgl.glfw.GLFW.GLFW_KEY_M;
        case "n": return org.lwjgl.glfw.GLFW.GLFW_KEY_N;
        case "o": return org.lwjgl.glfw.GLFW.GLFW_KEY_O;
        case "p": return org.lwjgl.glfw.GLFW.GLFW_KEY_P;
        case "q": return org.lwjgl.glfw.GLFW.GLFW_KEY_Q;
        case "r": return org.lwjgl.glfw.GLFW.GLFW_KEY_R;
        case "s": return org.lwjgl.glfw.GLFW.GLFW_KEY_S;
        case "t": return org.lwjgl.glfw.GLFW.GLFW_KEY_T;
        case "u": return org.lwjgl.glfw.GLFW.GLFW_KEY_U;
        case "v": return org.lwjgl.glfw.GLFW.GLFW_KEY_V;
        case "w": return org.lwjgl.glfw.GLFW.GLFW_KEY_W;
        case "x": return org.lwjgl.glfw.GLFW.GLFW_KEY_X;
        case "y": return org.lwjgl.glfw.GLFW.GLFW_KEY_Y;
        case "z": return org.lwjgl.glfw.GLFW.GLFW_KEY_Z;
        case "space": return org.lwjgl.glfw.GLFW.GLFW_KEY_SPACE;
        case "escape": return org.lwjgl.glfw.GLFW.GLFW_KEY_ESCAPE;
        case "enter": return org.lwjgl.glfw.GLFW.GLFW_KEY_ENTER;
        case "tab": return org.lwjgl.glfw.GLFW.GLFW_KEY_TAB;
        case "backspace": return org.lwjgl.glfw.GLFW.GLFW_KEY_BACKSPACE;
        case "insert": return org.lwjgl.glfw.GLFW.GLFW_KEY_INSERT;
        case "delete": return org.lwjgl.glfw.GLFW.GLFW_KEY_DELETE;
        case "right": return org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT;
        case "left": return org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT;
        case "down": return org.lwjgl.glfw.GLFW.GLFW_KEY_DOWN;
        case "up": return org.lwjgl.glfw.GLFW.GLFW_KEY_UP;
        case "left shift": return org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_SHIFT;
        case "right shift": return org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_SHIFT;
        case "left control": return org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_CONTROL;
        case "right control": return org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_CONTROL;
        case "left alt": return org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_ALT;
        case "right alt": return org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_ALT;
        case "1": return org.lwjgl.glfw.GLFW.GLFW_KEY_1;
        case "2": return org.lwjgl.glfw.GLFW.GLFW_KEY_2;
        case "3": return org.lwjgl.glfw.GLFW.GLFW_KEY_3;
        case "4": return org.lwjgl.glfw.GLFW.GLFW_KEY_4;
        case "5": return org.lwjgl.glfw.GLFW.GLFW_KEY_5;
        case "6": return org.lwjgl.glfw.GLFW.GLFW_KEY_6;
        case "7": return org.lwjgl.glfw.GLFW.GLFW_KEY_7;
        case "8": return org.lwjgl.glfw.GLFW.GLFW_KEY_8;
        case "9": return org.lwjgl.glfw.GLFW.GLFW_KEY_9;
        case "0": return org.lwjgl.glfw.GLFW.GLFW_KEY_0;
        case "-": return org.lwjgl.glfw.GLFW.GLFW_KEY_MINUS;
        case "=": return org.lwjgl.glfw.GLFW.GLFW_KEY_EQUAL;
        case "[": return org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_BRACKET;
        case "]": return org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_BRACKET;
        case "\\": return org.lwjgl.glfw.GLFW.GLFW_KEY_BACKSLASH;
        case ";": return org.lwjgl.glfw.GLFW.GLFW_KEY_SEMICOLON;
        case "'": return org.lwjgl.glfw.GLFW.GLFW_KEY_APOSTROPHE;
        case "`": return org.lwjgl.glfw.GLFW.GLFW_KEY_GRAVE_ACCENT;
        case ",": return org.lwjgl.glfw.GLFW.GLFW_KEY_COMMA;
        case ".": return org.lwjgl.glfw.GLFW.GLFW_KEY_PERIOD;
        case "/": return org.lwjgl.glfw.GLFW.GLFW_KEY_SLASH;
        default: return -1;
    }
}

    public static String[] shiftedKeyTable = {
        "",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Space",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "\"",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "<",
        "_",
        ">",
        "?",
        ")",
        "!",
        "@",
        "#",
        "$",
        "%",
        "^",
        "&",
        "*",
        "(",
        "Unknown",
        ":",
        "Unknown",
        "+",
        "Unknown",
        "Unknown",
        "Unknown",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "{",
        "|",
        "}",
        "Unknown",
        "Unknown",
        "~",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "World 1",
        "World 2",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Escape",
        "Enter",
        "Tab",
        "Backspace",
        "Insert",
        "Delete",
        "Right",
        "Left",
        "Down",
        "Up",
        "Page Up",
        "Page Down",
        "Home",
        "End",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Caps Lock",
        "Scroll Lock",
        "Num Lock",
        "Print Screen",
        "Pause",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "F11",
        "F12",
        "F13",
        "F14",
        "F15",
        "F16",
        "F17",
        "F18",
        "F19",
        "F20",
        "F21",
        "F22",
        "F23",
        "F24",
        "F25",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Unknown",
        "Num 0",
        "Num 1",
        "Num 2",
        "Num 3",
        "Num 4",
        "Num 5",
        "Num 6",
        "Num 7",
        "Num 8",
        "Num 9",
        "Num .",
        "Num /",
        "Num *",
        "Num -",
        "Num +",
        "Num Enter",
        "Num =",
        "Unknown",
        "Unknown",
        "Unknown",
        "Left Shift",
        "Left Control",
        "Left Alt",
        "Left Command",
        "Right Shift",
        "Right Control",
        "Right Alt",
        "Right Command",
        "Menu",
        "Last",
    };
}
